/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.hotel.view;

import com.poly.hotel.controller.HotelJFrameController;
import com.poly.hotel.util.XAuth;
import com.poly.hotel.view.manager.RoomCategoryManagerJDialog;
import com.poly.hotel.view.manager.RoomManagerJDialog;
import com.poly.hotel.view.manager.ServiceCategoryManagerJDialog;
import com.poly.hotel.view.manager.ServiceManagerJDialog;
import com.poly.hotel.view.manager.UserManagerJDialog;
import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author PHUONG LAM
 */
public class HotelJFrame extends javax.swing.JFrame implements HotelJFrameController {

    public void setMainPanelFromDialog(JDialog dialog) {
        // xóa component bên trong mainPanel
        mainPanel.removeAll();
        // lấy nội dung của dialog thêm vào mainPanel
        mainPanel.add(dialog.getContentPane());
        // update layout khi thay đổi
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * Creates new form HotelJFrame
     */
    public HotelJFrame() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/com/poly/hotel/icons/5-stars.png")).getImage();
        setIconImage(icon);
        lbFullName.setText(XAuth.user.getFullName());
        this.init();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnUserManager = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnRevenue = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnRoomManager = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        btnBill = new javax.swing.JButton();
        btnRoomCategoryManager = new javax.swing.JButton();
        btnServiceManager = new javax.swing.JButton();
        btnCategoryService = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        jMenuItem1.setText("Thanh toán");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cập nhật trạng thái");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/icons8-hotel-30.png"))); // NOI18N
        jLabel1.setText("Booking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        btnUserManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUserManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/user.png"))); // NOI18N
        btnUserManager.setText("QL Nhân viên");
        btnUserManager.setBorderPainted(false);
        btnUserManager.setContentAreaFilled(false);
        btnUserManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUserManager.setIconTextGap(10);
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 210, 50));

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/icons8-home-24.png"))); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIconTextGap(10);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 50));

        btnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/user.png"))); // NOI18N
        btnCustomer.setText("Khách hàng");
        btnCustomer.setBorderPainted(false);
        btnCustomer.setContentAreaFilled(false);
        btnCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCustomer.setIconTextGap(10);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 50));

        btnRevenue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/list.png"))); // NOI18N
        btnRevenue.setText("Doanh thu");
        btnRevenue.setBorderPainted(false);
        btnRevenue.setContentAreaFilled(false);
        btnRevenue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRevenue.setIconTextGap(10);
        btnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueActionPerformed(evt);
            }
        });
        jPanel1.add(btnRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 50));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/logout.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(10);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 50));

        btnRoomManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRoomManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/icons8-room-24.png"))); // NOI18N
        btnRoomManager.setText("Quản lý phòng");
        btnRoomManager.setBorderPainted(false);
        btnRoomManager.setContentAreaFilled(false);
        btnRoomManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRoomManager.setIconTextGap(10);
        btnRoomManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRoomManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nhân viên:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        lbFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbFullName.setForeground(new java.awt.Color(0, 0, 0));
        lbFullName.setText("Nguyễn Văn A");
        jPanel1.add(lbFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        btnBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/payment.png"))); // NOI18N
        btnBill.setText("Bill");
        btnBill.setBorderPainted(false);
        btnBill.setContentAreaFilled(false);
        btnBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBill.setIconTextGap(10);
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 50));

        btnRoomCategoryManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRoomCategoryManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/icons8-room-24.png"))); // NOI18N
        btnRoomCategoryManager.setText("QL Loại phòng");
        btnRoomCategoryManager.setBorderPainted(false);
        btnRoomCategoryManager.setContentAreaFilled(false);
        btnRoomCategoryManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRoomCategoryManager.setIconTextGap(10);
        btnRoomCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomCategoryManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRoomCategoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, 50));

        btnServiceManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnServiceManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/icons8-service-24.png"))); // NOI18N
        btnServiceManager.setText("Dịch vụ");
        btnServiceManager.setBorderPainted(false);
        btnServiceManager.setContentAreaFilled(false);
        btnServiceManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnServiceManager.setIconTextGap(10);
        btnServiceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnServiceManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, 50));

        btnCategoryService.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCategoryService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/hotel/icons/icons8-service-24.png"))); // NOI18N
        btnCategoryService.setText("QL Loại dịch vụ");
        btnCategoryService.setBorderPainted(false);
        btnCategoryService.setContentAreaFilled(false);
        btnCategoryService.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategoryService.setIconTextGap(10);
        btnCategoryService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryServiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategoryService, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 50));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1023, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new CustomerJDialog(this, true));
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new HomeJDialog(this, true));
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRoomCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomCategoryManagerActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new RoomCategoryManagerJDialog(this, true));
    }//GEN-LAST:event_btnRoomCategoryManagerActionPerformed

    private void btnRoomManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManagerActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new RoomManagerJDialog(this, true));
    }//GEN-LAST:event_btnRoomManagerActionPerformed

    private void btnServiceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceManagerActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new ServiceManagerJDialog(this, true));
    }//GEN-LAST:event_btnServiceManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new UserManagerJDialog(this, true));
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new BillJDialog(this, true));
    }//GEN-LAST:event_btnBillActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCategoryServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryServiceActionPerformed
        // TODO add your handling code here:
        setMainPanelFromDialog(new ServiceCategoryManagerJDialog(this, true));
    }//GEN-LAST:event_btnCategoryServiceActionPerformed

    private void btnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueActionPerformed
        // TODO add your handling code here:
        new RevenueJDialog();
    }//GEN-LAST:event_btnRevenueActionPerformed

    @Override
    public void init() {
        this.setLocationRelativeTo(null);
        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);
        setMainPanelFromDialog(new HomeJDialog(this, true));
        lbFullName.setText(XAuth.user.getFullName());
        if (!XAuth.user.getRole().equals("manager")) {
            btnRoomCategoryManager.setVisible(false);
            btnRoomManager.setVisible(false);
            btnCategoryService.setVisible(false);
            btnServiceManager.setVisible(false);
            btnUserManager.setVisible(false);
        }
    }
    
    @Override
    public Frame getFrame() {
        return this;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnCategoryService;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRevenue;
    private javax.swing.JButton btnRoomCategoryManager;
    private javax.swing.JButton btnRoomManager;
    private javax.swing.JButton btnServiceManager;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
